### PR TITLE
Swift 2.0 changes

### PR DESCRIPTION
**Pull request by elsesiy**
I updated the master branch to adapt Swift 2.0 language changes. 

Please review and merge, so others (as mentioned in #113) can use it as well :)

### CODE REVIEW

**Comment by elsesiy** [comment]
Now fixes also #87

**Comment by dgdosen** [comment]
thanks for adding a pull request.

**Comment by Mozharovsky** [comment]
@elsesiy: Thank you for the contribution! :]

**Comment by elsesiy** [comment]
@Mozharovsky You're welcome! Just let me know if I can support this project elsewhere, I'm glad to help! Love it!

**Comment by Mozharovsky** [comment]
@elsesiy: I appreciate your contribution a lot, thank you once more! If you wish to improve CVCalendar you could take a look at actual enhancements pointed out in #28. :smile:

**Comment by ngergo100** [comment]
Hi! I'm sorry to ask but how can i download the swift 2.0 version of the Calendar? If I download the master I got the old swift 1.2 version.

**Comment by elsesiy** [comment]
@ngergo100 If you're using the master-branch correctly, you actually should have the swift 2 version. Do you use cocoapods? If so, do you have the podfile updated to point to the right location?

**Comment by ngergo100** [comment]
@elsesiy Then i think i'm not using correctly, and i know i should use cocoapods but i don't, so could this be this problem?

**Comment by elsesiy** [comment]
@ngergo100 I don't think so. You just downloaded the zip from the master branch and imported the files into your project, right? That's basically the same as using cocoapods, so this shouldn't be a problem. I'll try reproducing your setup and let you know if it works for me.

**Comment by ngergo100** [comment]
Yeah, that's right! Thank you!

**Comment by elsesiy** [comment]
@ngergo100 It works flawlessly over here. There must be something wrong with your setup... have you added all the sources as compile time requirements?

**Comment by ngergo100** [comment]
@elsesiy I think i've added all. But i will try again. Thanks for the feedback. I will let you know if i succeeded.

**Comment by ngergo100** [comment]
@elsesiy I think now I've succeeded. It's working now, but i still got 31 warnings. Is that okay?
screen shot 2015-09-24 at 16 24 38

**Comment by elsesiy** [comment]
@ngergo100 that's fine, they doesn't affect the functionality. I'll be fixing them soon!

**Pull request merged**
