### PR TITLE
Dot marker size can be varied using a delegate 'sizeOnDayView' -> flo…

### PR DESCRIPTION
**Pull request by sandeepmenon**
Eugene,

Added a delegate to control the size of dot marker to have flexible size according to screen. Have tested it and works fine. Hope it helps!

Sandeep

### CODE REVIEW

**Comment by Mozharovsky** [comment]
Hello @sandeepmenon, 

Thank you for your contribution!

Please, update the changes to the current master branch, so the merge can be completed. :) 

Regards, 
Eugene

**Comment by sandeepmenon** [comment]
i have updated the branch :D .. timing of creating a request was bit off

**Comment by Mozharovsky** [comment]
Thank you once more! :+1:

**Comment by Mozharovsky** [comment]
Please, could you document the changes?

**Comment by sandeepmenon** [comment]
i have updated only the CV calendar under the project and not on the top level. Should i update both?

Sure i will update the documentation

**Comment by Mozharovsky** [comment]
Yes, both CVCalendar(s) should be updated. :] 

Thank you!

**Pull request merged**
