### PR TITLE
Added the ability to change the weekday symbol type for the CVCalendarMenu

### PR DESCRIPTION
**Pull request by roymckenzie**
Hello, all! First pull request here. Would like to add the ability to change the weekday symbol type for the Calendar Menu. Uses an enum to allow easy selection. Selection is made on the delegate for CVCalendarMenuViewDelegate. 🖖🏻

### CODE REVIEW

**Comment by Mozharovsky** [comment]
Hello @roymckenzie, 

Thank you for your useful contribution!

Please, could you update the changes to the most recent code on the master branch, so it won't be conflicting while merging? 

Regards, 
Eugene

**Comment by roymckenzie** [comment]
Fixed @Mozharovsky!

**Comment by Mozharovsky** [comment]
Thank you so much once more! :+1:

**Comment by Mozharovsky** [comment]
Please, could you document the changes?

**Comment by roymckenzie** [comment]
Hey @Mozharovsky I don't see documentation for the `CVCalendarMenuViewDelegate`. Can you point me to it and I will update?

**Comment by Mozharovsky** [comment]
@roymckenzie, there is no page on wiki but feel free to add one! :)

**Comment by roymckenzie** [comment]
Ohh! I see what you are trying to do! :) Happy to help and I will try to add one this evening.

**Pull request merged**
