### PR TITLE
Adds a way to use a custom shape for single selection instead of the default circle

### PR DESCRIPTION
**Pull request by ts-alexandros**

### CODE REVIEW

**Comment by elsesiy** [comment]
Hi @ts-alexandros, thanks for your contribution, we really appreciate the help!
Your addition looks fine to me except the addition in CVCalendarViewAnimator#animateSelectionOnDayView as stated here:
https://github.com/Mozharovsky/CVCalendar/commit/87966ffe87d2bd0be4dc60ccf0c01b4351e43316

**Comment by stefreak** [comment]
@retendo @ts-alexandros can you comment on this?

**Comment by rhenz** [comment]
Hi guys. When do you plan to merge this up? :)

**Comment by elsesiy** [comment]
@rhenz As soon as my remarks have been clarified..

**Comment by retendo** [comment]
Ah sorry, we just copied over the files from the demo project, where we tested the changes. We will revert the added line in the library source today.

**Comment by ts-alexandros** [comment]
I just removed the accidentally added code. @elsesiy is it ok now?

**Comment by elsesiy** [comment]
@ts-alexandros It's still in the lib project...

**Comment by ts-alexandros** [comment]
Oops, sorry, we edited the wrong file. Should be fine now

**Comment by elsesiy** [comment]
Great -> merged

**Pull request merged**
