### PR TITLE
update for swift2.2

### PR DESCRIPTION
**Pull request by sairamkotha**

### CODE REVIEW

**Comment by elsesiy** [comment]
@sairamkotha Thanks for contributing! I'm just curious, why have you replaced the ++ with +=1 except for the AnyGenerator in CVSet?

**Comment by sairamkotha** [comment]
because ++ -- increment operator are deprecated in swift 2.2 & It will be removed in swift 3.0. So update ++ to +=1

**Comment by sairamkotha** [comment]
check this apple swift evolution github link
https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md

**Comment by elsesiy** [comment]
@sairamkotha I know the facts, my point is that you still miss one line where you haven't replaced it..

**Comment by sairamkotha** [comment]
Ya got it. I will do it by end of the day & I will push @elsesiy

**Comment by sairamkotha** [comment]
@elsesiy  now check two commits and merge :)

**Comment by danielbmarques** [comment]
@elsesiy I think @sairamkotha's code in the last commit actually changes the operator instead of just updating the syntax. With `power++`, as it were before, `nextClosure` would start returning 1. Now it starts returning 0.

**Comment by danielbmarques** [comment]
@elsesiy Also these fixes aren't in the main CVCalendar directory, just in the demo. I fixed the code in CVCalendar myself, should I make a PR? 
There are a lot of other differences between CVCalendar and the demo too, that should be fixed, but I don't know what changes to keep from what files.

**Comment by danielbmarques** [comment]
This is a real mess, there are many changes to the main directory that weren't updated in the demo and vice-versa. Now I don't know what to keep from what files.

**Comment by danielbmarques** [comment]
@elsesiy I tried to merged the changes in the CVCalendar and Demo directories and made a PR, #261.

**Comment by elsesiy** [comment]
@danielbmarques Since the Demo will soon use a Symlink to the CVCalendar-Folder, this should be fine. Thanks for submitting the PR, it's true that some of the enhancement were only in the actual lib since this is the more important part of this project (Pod, Carthage).

**Pull request merged**
