### PR TITLE
sup view frame bug fix

### PR DESCRIPTION
**Pull request by gregazevedo**
Supplementary and preliminary view frames are calculated to be on the weekview. This fix adds these views as subviews of the weekview instead of the dayview

### CODE REVIEW

**Comment by elsesiy** [comment]
Can you please explain how this is beneficial?

**Comment by gregazevedo** [comment]
@elsesiy There is a bug when adding a supplementary or preliminary view. These views frames are calculated to be on the weekView and are added to the dayView currently instead

**Comment by elsesiy** [comment]
@gregazevedo I don't see any error actually and replicating your changes result in the subviews being drawn only on the first day of the week in the Demo Project. So could you please elaborate on what the problem is?

**Comment by elsesiy** [comment]
Since @gregazevedo didn't clarify the issue, closed.

**Pull request closed without merging**
