### PR TITLE
Refresh topMarker and dotMarker too in refreshPresentedMonth()

### PR DESCRIPTION
**Pull request by neugartf**

### CODE REVIEW

**Comment by joelwass** [comment]
good catch

**Comment by neugartf** [comment]
thx ;)
i think "removeDotViews(dayView)" is redundant then, setupDotMarker already removes the dotmarker from the parentView. But that's your call i guess

**Comment by joelwass** [comment]
eh not my call i don't have contribute rights to this repo, i'm a user just like you. i don't use the dot markers so i was mainly just doing it for others with the issue... 

i guess if it's redundant it might be worth while to take out my portion and recommit with your fix

**Comment by elsesiy** [comment]
Fixed in https://github.com/Mozharovsky/CVCalendar/commit/b29744a798b639c546602de825cd5159512be37d

**Pull request closed without merging**
