### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by Antoine4011**

### CODE REVIEW

**Comment by elsesiy** [comment]
This is a breaking change and since Swift 3 hasn't been released officially yet, I won't merge at this point in time. I'll leave it open and reconsider after Sep, 13th.

**Comment by rmickeyd** [comment]
Xcode 8 GM is out.  Please merge.

**Comment by elsesiy** [comment]
@rmickeyd Even GM is out, I'll wait for final release of iOS 10 before merging in oder to validate functionality..

**Comment by alexpja** [comment]
@elsesiy iOS 10 has been released.

**Comment by yuanjilee** [comment]
also not support Swift 3.0?

**Comment by elsesiy** [comment]
I'll upgrade the library to Swift 3 syntax soon and release a new major version.

**Comment by Fawxy** [comment]
Looking forward to this being merged! You're my last swift 2 library ;)

**Comment by elsesiy** [comment]
I just merged the PR, thanks @Antoine4011 
There's currently an issue with cocoapods, so please specify master directly in the Podfile..

**Pull request merged**
