### PR TITLE
Show Months delegate methods

### PR DESCRIPTION
**Pull request by nexon**
This PR add two delegates methods that are called when the user scroll left or right.

### CODE REVIEW

**Comment by Mozharovsky** [comment]
Hello @nexon, 

Thank you for the contribution! 

I'm not sure if the naming provided for protocol methods is descriptive enough. It might be worth renaming those methods, so it's absolutely obvious what happens once a method is called. I suggest to change names from `showNextMonthView` to `didShowNextMonthView`. 

Regards, 
Eugene

**Comment by nexon** [comment]
Hi @Mozharovsky thanks for the fast reply. Regarding the naming... yes there aren't so descriptives. I was thinking in  `didShowNextMonthView` but (at least for me) sounds that this method should return `true` or `false`.

Any ideas?

**Comment by Mozharovsky** [comment]
That fits all the requirements. Besides, Apple engineers use such naming pattern in their API. Should be just fine! :]

**Comment by nexon** [comment]
Okay, i will change the names!.

Thanks!

**Comment by Mozharovsky** [comment]
Thank you!

**Comment by nexon** [comment]
Okay, PR updated.

**Pull request merged**
